version: '3.7'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
            - 82:80
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - ${SYMFONY_APP}:/home/swoma/api
        depends_on:
            - php
        networks:
            default:
                aliases:
                    - 'api.swoma.local'

    mysql:
        image: mysql:5.7
        container_name: sf4_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
            - ${SYMFONY_APP}:/home/swoma/api
        environment:
            - maildev_host=sf4_maildev
        depends_on:
            - maildev
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        restart: always
        ports:
            - 8080:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql
        networks:
            default:
                aliases:
                    - 'phpmyadmin.swoma.local'

    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - 8001:80
        networks:
            default:
                aliases:
                    - 'maildev.swoma.local'

    nginx:
        container_name: angular_nginx
        build: .docker/nginx
        volumes:
            - ${ANGULAR_APP}/dist/ng:/usr/share/nginx/html
        ports:
            - "81:80"
            - "443:443"
        networks:
            default:
                aliases:
                    - 'ng.swoma.local'

    node:
        build: .docker/node
        container_name: angular_node
        ports:
            - 4200:4200
        volumes:
            - ${ANGULAR_APP}:/home/node/swoma/ng
        tty: true
        command:
            - /bin/sh
            - -c
            - cd /home/node/swoma/ng && npm start
        expose:
            - "4200"
