version: '3.7'
services:
    apache:
        build: .docker/apache
        container_name: 'back_apache'
        ports:
            - "8004:80"
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - ${BACK_APP}:/home/${APP_NAME}/${BACK_APP}
        depends_on:
            - php
        networks:
            default:
                aliases:
                    - 'api.${APP_NAME}.local'
                    - 'api'

    mysql:
        image: mysql:5.7
        container_name: 'back_mysql'
        volumes:
            - .docker/data/db:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            default:
                aliases:
                    - 'mysql.${APP_NAME}.local'
                    - 'mysql'

    php:
        build: .docker/php
        container_name: 'back_php'
        volumes:
            - ${BACK_APP}:/home/${APP_NAME}/${BACK_APP}
        environment:
            - maildev_host=${BACK_APP}_maildev
        depends_on:
            - maildev
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'back_phpmyadmin'
        restart: always
        ports:
            - "8002:80"
        links:
            - mysql
        environment:
            PMA_HOST: mysql
        networks:
            default:
                aliases:
                    - 'phpmyadmin.${APP_NAME}.local'

    maildev:
        image: djfarrelly/maildev
        container_name: 'back_maildev'
        ports:
          - "8001:80"
        networks:
            default:
                aliases:
                    - 'maildev.${APP_NAME}.local'

    nginx:
        container_name: 'front_nginx'
        build: .docker/nginx
        volumes:
            - ${FRONT_APP}/dist:/usr/share/nginx/html
        ports:
            - "80:80"
            - "443:443"
        networks:
            default:
                aliases:
                    - 'app.${APP_NAME}.local'

    node:
        build: .docker/node
        container_name: 'front_node'
        ports:
            - "4200:4200"
        volumes:
            - ${FRONT_APP}:/home/node/${APP_NAME}/${FRONT_APP}
        tty: true
        expose:
            - "4200"
